### ISSUE TITLE
Cannot Open Image File

### ISSUE THREAD

**Issue by ashiq24** [RFShahrear/CSEFest18Bomberman#1]
I just wanted to simulate the game . And executed the programme Visual.py and got the following error .

Scheduling Move
Scheduling Move
Executing Tick
Traceback (most recent call last):
  File "Visual.py", line 204, in <module>
    main()
  File "Visual.py", line 196, in main
    game.update_map(players)
  File "Visual.py", line 98, in update_map
    self.gameDisplay.blit(self.get_image(image),
  File "Visual.py", line 53, in get_image
    image = pygame.image.load("Images\\" + canonized_path)
pygame.error: Couldn't open Images\unbreakwall.png

**Comment by RFShahrear** [comment]
Did you download the entire repository, including the Images folder? If you have, try running your IDLE/IDE as administrator.

**Comment by ashiq24** [comment]
Yes i have downloaded entire repository. I am in linux and executing this from command line . I also searched the image folder for this image .And i found that image .I don't know why it is behaving in this way

**Comment by aahmed109** [comment]
As you're in Linux, I think to change from "Images\\" to "Images/" will solve the problem

**Comment by ashiq24** [comment]
ok vai

**Comment by RFShahrear** [comment]
should be fixed in https://github.com/RFShahrear/CSEFest18Bomberman/commit/a5ba4d7a140ea54574fbdb30134a512af5597928
