### ISSUE TITLE
Some confusions...

### ISSUE THREAD

**Issue by ashiq24** [RFShahrear/CSEFest18Bomberman#2]
in the graph p1,p2,p3,p4 will denote 4 players .But which one will indicate my location ?
what is the initial bomb count  for each player ?
what is the time interval(how many ticks) between placing a bomb and bursting it ?
what is the radius of the bomb ?
should we need to find it out by inspection the code ??

**Comment by RFShahrear** [comment]
Originally you were to call get_self_data to get info about your position. I may have accidentally removed it, sorry about that. I've also added an index parameter which will be initialized when you are added to the map. The index denotes -
1 - Upper Left
2 - Lower Right
3 - Lower Left
4 - Upper Right

Please download the latest version to get this change.

Time interval is 10 ticks. This may be subject to change.

Initial bomb count is 1 for each player.
Radius is 1 block, in each direction.
Both of these are visible in the left panel.

Feel free to ask or inspect, or both, whichever you prefer.

Remember to close the issue if it is resolved.
