### ISSUE TITLE
More confusion

### ISSUE THREAD

**Issue by ashiq24** [RFShahrear/CSEFest18Bomberman#3]
what get_player_data(self, target_player_index) function will return ?  and what is target player index ?

I am not under the restart issue "reset restart to false when it's true and then starting next round"?
it will be better if explained clearly .
thank you

**Comment by RFShahrear** [comment]
The target player index is basically 1,2 (for 2 player) and 1-4 for 4 player. it will return the information stated in the readme.

> Player Data : A Dictionary Containing
    "coordinate"                         -> Position
    "bomb_size"                         -> Explosion Radius
    "bomb_count"                      -> Number of Bombs that can be deployed at a time
    "index"                                 -> Player Index

If you want info on all players, you will have to call it 1 to 3 times, depending on player count. You will not be informed the number of players on the field, think of a way to handle that.

I have changed the readme to better clarify the steps.

**Comment by ashiq24** [comment]
please also give the limit of the game  board dimensions.

**Comment by RFShahrear** [comment]
You can call a get_full_map and find out it's length. Assume that the size can be anything.
