### ISSUE TITLE
#Confusion_and_confusion

### ISSUE THREAD

**Issue by ghost** [RFShahrear/CSEFest18Bomberman#4]
1.How to get other player's,where they are placing boms,destructable walls co ordinate?.

2.You told about the parameters namely : restart, done, success, index.  Well, do i have to pass it through play method or i can write my own method??

3.About the map:

* what is the point of second portion of the map?.The visual.py does't do anything about that?.then why that part is available?.I mean:
".................
.................
.....+...........
.................
.................
.................
.................
.................
.................
.................
.................
.................
.................
................."   this part?

Hoping for the solution to those ""can't understand issues"" .Thanks.
(n.b:I might ask some dumb questions but to be honest i can't get those points)

**Comment by RFShahrear** [comment]
1. If you need player specific position, you will need to call get_player_data multiple times and check coordinates there. For any other coordinate, call get_full_map, iterate through it to find what you need.

2. You need these parameters initialized in the __init__ function of your class, success as True, restart and over as False. Index as anything you want. It will be properly initialized when it is called.  Look over the sample player file to see how these variables are used. **You do not need to have them as the parameter to any method**. You are free to create your own methods. Although we do encourage you to keep to main playing loop in the play function. You will not be penalized for not doing so. I have changed the readme to make it clearer.

3. That is the power up map. It indicates where the power ups are hidden. You will not be privy to this information during your play. You will only know the position of a power up when it is revealed. This is strictly a processor side information.
