### ISSUE TITLE
player.over not being set.

### ISSUE THREAD

**Issue by nafiz6** [RFShahrear/CSEFest18Bomberman#5]
When my character dies in an explosion, the self.over variable isn't being set to true, so my character reappears on the map. Do I have to manually check if my character was in an explosion and set the variable to true?

PS: I looked into the processor code. The part which is supposed to set the player.over variable to true checks the condition if the y coordinate of the player is equal to the pair coordinates of the bomb (line 139 of Processor.py). Shouldn't the line be
 "if self.__player_data[player]["coordinate"] == (bomb[1][0] +i+1 ,bomb[1][1])" ?
I may be completely wrong so please correct me.

**Comment by RFShahrear** [comment]
Yes, you are correct, it should update over properly now. Update to the latest version for the fix.
